### ISSUE TITLE
The Game Crash "Cannot create a fluidstack from an unregistered fluid" if I don't open Extra Planets config file before

### ISSUE THREAD

**Issue by Mathegyl** [Arrokoth486958/The_Sol-A_Galacticraft_addon#5]
Since i have aad this mod https://discord.com/channels/309283659935121409/808766406699122728/1043956570528165921 To my Modpack (it add only 4 blocks for a Star Maker Dimension), I Can't start Minecraft without crash if i don't open Extra Planet Config files...

The Error Is :

> java.lang.ExceptionInInitializerError
	at mod.sol.util.handler.RenderHandler.registerCustomMeshesAndStates(RenderHandler.java:15)
	at mod.sol.util.handler.RegistryHandler.onBlockMeshRegister(RegistryHandler.java:42)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_145_RegistryHandler_onBlockMeshRegister_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from an unregistered fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:54)
	at net.minecraftforge.fluids.BlockFluidClassic.<init>(BlockFluidClassic.java:63)
	at net.minecraftforge.fluids.BlockFluidClassic.<init>(BlockFluidClassic.java:68)
	at mod.sol.blocks.BlockFluidBase.<init>(BlockFluidBase.java:17)
	at mod.sol.init.SolBlocks.<clinit>(SolBlocks.java:22)
	... 18 more

I don't know why that error is linked to a mod that cotan 4 blocks and to the config file of Extra Planets but this is my problem.

I Use the lastest version of The Sol present in GitHub

**Comment by Mathegyl** [comment]
[crash-2022-11-23_13.57.32-client.txt](https://github.com/Arrokoth486958/The_Sol-A_Galacticraft_addon/files/10076762/crash-2022-11-23_13.57.32-client.txt)
[2022-11-23-5.log.gz](https://github.com/Arrokoth486958/The_Sol-A_Galacticraft_addon/files/10076774/2022-11-23-5.log.gz)

**Comment by Arrokoth486958** [comment]
Sry no updates more :/

**Comment by Mathegyl** [comment]
Okay so can i try to tweak or fork the mod to repare the error ?

**Comment by Arrokoth486958** [comment]
Sure

从 Windows 版邮件发送

发件人: Mathegyl
发送时间: 2022年11月30日 19:56
收件人: Arrokoth486958/The_Sol-A_Galacticraft_addon
抄送: Arrokoth233; Comment
主题: Re: [Arrokoth486958/The_Sol-A_Galacticraft_addon] The Game Crash"Cannot create a fluidstack from an unregistered fluid" if I don't open ExtraPlanets config file before (Issue #5)

Okay so can y try to tweak or fork the mod to repare the error ?

**Comment by Mathegyl** [comment]
Problem soved by updating the 4 block mod that make appear that bug
